### ISSUE TITLE
Auto lock timeout

### ISSUE THREAD

**Issue by jdmarlow86** [pbca26/agama-mobile#11]
1. Saved settings with a 10 minute lock timeout
2. Went back to the Dashboard
3. Let app/phone sit idle for 15 minutes
4. Lockout never occured

**Comment by jdmarlow86** [comment]
Time for auto lock is now cut in half. 10 min = 5 min, 20=10, etc

**Comment by jdmarlow86** [comment]
Now all options time out at 10 mins

**Comment by pbca26** [comment]
will check

**Comment by jdmarlow86** [comment]
Retest pass, ok to close
