### ISSUE TITLE
BCH not received on AGAMA-MOBILE

### ISSUE THREAD

**Issue by Rixster88** [pbca26/agama-mobile#2]
Hi there. On January 29th i sent BCH to my Agama wallet and it isnt showing on the app, I only get the error message "Connection error. Please try another BCH server."both servers aren't working. On block dozed I can see the that the transaction was successful but my BCH is no where to be seen.
Please advise

**Comment by pbca26** [comment]
BCH Electrum servers are offline due to address compatibility issue that was included recently in all bch nodes. Unfortunately until necessary changes are merged into Electrum' code BCH will stay down.

You can still get your priv keys from Agama and import into any other piece of software. To do that you'd need to use Agama desktop version.

**Comment by Rixster88** [comment]
So if I don't have a desktop pc to access AGAMA on I can't access my BCH?

On 06 Feb 2018 12:33 PM, "pbca26" <notifications@github.com> wrote:

BCH Electrum servers are offline due to address compatibility issue that
was included recently in all bch nodes. Unfortunately until necessary
changes are merged into Electrum' code BCH will stay down.

You can still get your priv keys from Agama and import into any other piece
of software. To do that you'd need to use Agama desktop version.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pbca26/agama-mobile/issues/2#issuecomment-363380716>,
or mute the thread

**Comment by pbca26** [comment]
that's not what i meant
your funds are on blockchain and not in a specific wallet
agama desktop is to get your priv keys
but you will have to use another wallet that does have a full bch support
