### ISSUE TITLE
[Account creation / Import] - Feature request. Add copy to clipboard button for seed and save to file button for QR.

### ISSUE THREAD

**Issue by tonymorony** [pbca26/agama-mobile#26]
![create_seed](https://user-images.githubusercontent.com/24797699/53608880-0f3b0d80-3bf7-11e9-91c4-fac86533a851.jpg)

At the moment there is no way to save this data except manual selecting, moreover, such manual selecting ***allows to grab extra space.***

Copy to clipboard button will allow the user to reliable copy his seed + in future will be possible to add validation with "I'm saved seed" tick where the user has to paste his seed to confirm the match before next step proceeds.

Also not sure that many users know how to do manually screenshot from their phone to save the seed.

Extra space:
![extra_space](https://user-images.githubusercontent.com/24797699/53609995-ef5a1880-3bfb-11e9-9f5c-4806c13557a3.png)

**Comment by pbca26** [comment]
![s90301-115406](https://user-images.githubusercontent.com/7769879/53627309-2f7bc400-3c19-11e9-98ee-3cd743ef80e7.jpg)
this is what i have, no extra space
have you checked after copy-pasting that it does actually contain an extra space or is it just a rendering issue?

**Comment by tonymorony** [comment]
On paste it had extra /n

**Comment by tonymorony** [comment]
video: https://s3.us-east-2.amazonaws.com/tonyl777/seed_copy_paste.mp4

actually, it's possible to copy a content of the whole page (selector not locking on the field with seed) - just noticed. So I wonder you just select it carefully.

**Comment by tonymorony** [comment]
Realized now that it'll not help much if the user will paste it with an error then.

Maybe in future, it'll be possible to make this process as in BitPay wallet: you no need to input pre-generated seed on the first login but can export it later or on creation process if click export button. It helps to avoid the problem when users initially sending funds to the address generated by misspelled seed pasting (more than half of Agama desktop support tickets regards such problem)

**Comment by pbca26** [comment]
that makes sense
although i'm a fan of ledger's seed confirm flow

**Comment by tonymorony** [comment]
Process was improved with words confirmation
